package View;

import Model.BienToanCuc;
import Model.ChuDe;
import Model.TuVung;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * class: đại diện chức năng ôn tập
 */
public class OnTapTuVung extends javax.swing.JFrame {

    /**
     * Creates new form OnTapTuVung
     */
    public OnTapTuVung() {
        initComponents();
        // Chu de co tat ca cac tu , sap xep
        for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() )
            for( TuVung tv : cd.getDanhSachTu() ) {
                allWord.addTu(tv);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        WordShow = new javax.swing.JLabel();
        DAPAN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PhienAm = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TuLoai = new javax.swing.JTextPane();
        LabelImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Nghia = new javax.swing.JTextPane();
        DAUHOI = new javax.swing.JLabel();
        TIEP = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CHUDE = new javax.swing.JLabel();
        RESET = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 120));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("ÔN TẬP TỪ VỰNG");

        WordShow.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        DAPAN.setText("ĐÁP ÁN");
        DAPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAPANActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(PhienAm);

        jScrollPane2.setViewportView(TuLoai);

        jScrollPane3.setViewportView(Nghia);

        DAUHOI.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        TIEP.setText("TIẾP");
        TIEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIEPActionPerformed(evt);
            }
        });

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        jLabel3.setText("CHỦ ĐỀ");

        CHUDE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        RESET.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RESET.setText("ÔN TẬP LẠI TỪ ĐẦU");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CHUDE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DAPAN, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(TIEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(WordShow, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3)
                                    .addComponent(LabelImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(BACK))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BACK))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DAUHOI, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CHUDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WordShow, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DAPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TIEP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ChuDe allWord = new ChuDe(); // chủ đề chứa tât cả các từ
    int j; // biến lưu lại vị trí ôn tập
    File fileCountReview = new File("manage\\countReview.txt"); // file quản lí biên ôn tập
    /**
     * hàm thiết lập khi mở cửa sổ chính thì show ra màn hình ( tự định nghĩa )
     * @param evt 
     */
    private void formWindowOpenedNew(ActionEvent evt) {                                  
        PhienAm.setText(null);
        TuLoai.setText(null);
        Nghia.setText(null);
        LabelImage.setIcon(null);
        try {
            Scanner sc = new Scanner(fileCountReview);
            j = sc.nextInt();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HocTuVung.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TuVung wordTemp = allWord.getDanhSachTu().get(j);
        WordShow.setText(wordTemp.getTenTu());
        DAUHOI.setText("????");
        ChuDe topicTemp = new ChuDe();
            for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) 
                for(TuVung tu : cd.getDanhSachTu() ) {
                    if( tu == wordTemp ) { topicTemp = cd; break; }
            }
        CHUDE.setText(topicTemp.getTenChuDe());
    }
    /**
     * thiết lập hiển thị đáp án
     * @param evt 
     */
    private void DAPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAPANActionPerformed
        TuVung wordTemp = new TuVung();
        ChuDe topicTemp = new ChuDe();
        for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) 
                for(TuVung tv : cd.getDanhSachTu() ) {
                    if( tv.getTenTu().equals(WordShow.getText()) ) { topicTemp = cd; wordTemp = tv; break; }
            }
        CHUDE.setText(topicTemp.getTenChuDe());
        DAUHOI.setText(null);
        PhienAm.setText(wordTemp.getPhienAm());
        TuLoai.setText(wordTemp.getTuLoai());
        Nghia.setText(wordTemp.getNghia());
        // điều chỉnh kích thước cho ảnh vừa với Label
        ImageIcon icon = new ImageIcon(wordTemp.getLinkImage());
        Image image = icon.getImage().getScaledInstance(LabelImage.getWidth(), LabelImage.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(image, icon.getDescription());
        LabelImage.setIcon(icon);
    }//GEN-LAST:event_DAPANActionPerformed
    /**
     * chuyển câu hỏi
     * @param evt 
     */
    private void TIEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIEPActionPerformed
        try {
            // kiem tra so tu da hoc, va khi on tap
            File fileCount = new File("manage\\count.txt");
            Scanner scCount = new Scanner(fileCount);
            int i = scCount.nextInt();
            if( j >= i ) { JOptionPane.showMessageDialog(this,"Đã ôn tập hết từ đã học","Message Dialog Demo",JOptionPane.INFORMATION_MESSAGE); return; }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OnTapTuVung.class.getName()).log(Level.SEVERE, null, ex);
        }
        // hien thi tren man hinh
        PhienAm.setText(null);
        TuLoai.setText(null);
        Nghia.setText(null);
        LabelImage.setIcon(null);
        j++;
        TuVung wordTemp = allWord.getDanhSachTu().get(j);
        WordShow.setText(wordTemp.getTenTu());
        DAUHOI.setText("????");
        ChuDe topicTemp = new ChuDe();
            for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) 
                for(TuVung tu : cd.getDanhSachTu() ) {
                    if( tu == wordTemp ) { topicTemp = cd; break; }
            }
        CHUDE.setText(topicTemp.getTenChuDe());
    }//GEN-LAST:event_TIEPActionPerformed
    /**
     * đóng cửa sổ hiện tại , mở cửa sổ ban đầu ra
     * @param evt 
     */
    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new MainProgram().setVisible(true);
        this.dispose();        
        try {
            File fileCount = new File("manage\\countReview.txt"); 
            FileWriter fw = new FileWriter(fileCount.getAbsoluteFile());
            fw.write(String.valueOf(j));
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(HocTuVung.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_BACKActionPerformed
    /**
     * thiết lập để ôn tập lại từ đầu
     * @param evt 
     */
    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        int check = JOptionPane.showConfirmDialog(null,"Bạn có thực sự muốn ôn tập lại từ đầu?","", JOptionPane.YES_NO_OPTION);
        if( check == 0 ) {
            try {
                File fileCount = new File("manage\\countReview.txt"); 
                FileWriter fw = new FileWriter(fileCount.getAbsoluteFile());
                fw.write(String.valueOf(0));
                fw.close();
                JOptionPane.showMessageDialog(this,"XONG","Message Dialog Demo",JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(HocTuVung.class.getName()).log(Level.SEVERE, null, ex);
            }
            formWindowOpenedNew(evt);
        }
    }//GEN-LAST:event_RESETActionPerformed
    /**
     * hàm thiết lập khi mở cửa sổ chính thì show ra màn hình ( java Swing định nghĩa )
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Scanner sc = new Scanner(fileCountReview);
            j = sc.nextInt();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HocTuVung.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TuVung wordTemp = allWord.getDanhSachTu().get(j);
        WordShow.setText(wordTemp.getTenTu());
        DAUHOI.setText("????");
        ChuDe topicTemp = new ChuDe();
            for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) 
                for(TuVung tu : cd.getDanhSachTu() ) {
                    if( tu == wordTemp ) { topicTemp = cd; break; }
            }
        CHUDE.setText(topicTemp.getTenChuDe());
    }//GEN-LAST:event_formWindowOpened

    /**
     * hàm main
     * @param args 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnTapTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnTapTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnTapTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnTapTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnTapTuVung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JLabel CHUDE;
    private javax.swing.JButton DAPAN;
    private javax.swing.JLabel DAUHOI;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JTextPane Nghia;
    private javax.swing.JTextPane PhienAm;
    private javax.swing.JButton RESET;
    private javax.swing.JButton TIEP;
    private javax.swing.JTextPane TuLoai;
    private javax.swing.JLabel WordShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
