package View;

import Controller.IOFile;
import Model.BienToanCuc;
import Model.ChuDe;
import Model.TuVung;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 * class: tra cứu từ vựng
 */
public class TraCuuTuVung extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    public TraCuuTuVung() {
        initComponents();
        // khởi tạo combo box ngay khi mở cửa sổ
        BoxTopicAndAll.addItem("ALL");
        for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) {
            BoxTopicAndAll.addItem(cd.getTenChuDe());
        }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        keyWord = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWordSelect = new javax.swing.JList<>();
        BoxTopicAndAll = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        panePhienAm = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        paneTuLoai = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        paneNghia = new javax.swing.JTextPane();
        LabelImage = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PaneTenTu = new javax.swing.JTextPane();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        keyWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyWordKeyTyped(evt);
            }
        });

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("TRA CỨU TỪ VỰNG");

        listWordSelect.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordSelectValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWordSelect);

        BoxTopicAndAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxTopicAndAllActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(panePhienAm);

        jScrollPane5.setViewportView(paneTuLoai);

        jScrollPane6.setViewportView(paneNghia);

        LabelImage.setPreferredSize(new java.awt.Dimension(234, 198));

        jScrollPane7.setViewportView(PaneTenTu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keyWord, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoxTopicAndAll, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(14, 14, 14)
                        .addComponent(BoxTopicAndAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(keyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * khi nhập từ bàn phím , màn hình sẽ nhảy đến từ gợi ý
     * @param evt 
     */
    private void keyWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyWordKeyTyped
        String text = keyWord.getText().trim();
        text += evt.getKeyChar();
        text = text.trim();
        
        for(int i = 0 ; i < mod.size() ; i++ ) {
            String keyWord = mod.getElementAt(i);
            if( keyWord.startsWith(text) ) {
                listWordSelect.setSelectedIndex(i);
                return;
            }
        }
        panePhienAm.setText(null);
        paneTuLoai.setText(null);
        paneNghia.setText(null);
        LabelImage.setIcon(null);        
    }//GEN-LAST:event_keyWordKeyTyped
   /**
    * đóng cửa sổ, mở lại màn hình chính
    * @param evt 
    */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new MainProgram().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private DefaultListModel<String> mod; // list hiển thị từ ra ngoài màn hình
    private ArrayList<TuVung> arr; // danh sách từ vựng
    /**
     * show ra màn hình ngay khi mở cửa sổ ( tự định nghĩa )
     * @param evt 
     */
    private void formWindowOpenedNew(ActionEvent evt) {
        // đưa dữ liệu vào danh sách thả xuống
        mod = new DefaultListModel<>();
        listWordSelect.setModel(mod);
        arr = new ArrayList<>();
        String nameTemp = BoxTopicAndAll.getSelectedItem().toString();
        System.out.println("bat dau");
        System.out.println(nameTemp);
        // tạo 1 chủ đề tạm set tên giống chủ đề trong danh sách thực
        ChuDe topicTemp = new ChuDe();
        
        for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) {
            if( cd.getTenChuDe().equals( nameTemp )) { topicTemp = cd; break; }
        }
        for( TuVung tv : topicTemp.getDanhSachTu() ) {
            arr.add(tv);
            mod.addElement(tv.getTenTu());
        }

        for( TuVung tv : topicTemp.getDanhSachTu() ) {
            System.out.println(tv.getTenTu());
        }
    }
    /**
     * hiển thị ra thông tin ngay khi chọn vào 1 từ nào đó
     * @param evt 
     */
    private void listWordSelectValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordSelectValueChanged
        if( !listWordSelect.isSelectionEmpty() ) {
            int index = listWordSelect.getSelectedIndex();
            TuVung temp = arr.get(index);
            PaneTenTu.setText(temp.getTenTu());
            panePhienAm.setText(temp.getPhienAm());
            paneTuLoai.setText(temp.getTuLoai());
            paneNghia.setText(temp.getNghia());
            // điều chỉnh kích thước cho ảnh vừa với Label
            ImageIcon icon = new ImageIcon(temp.getLinkImage());
            Image image = icon.getImage().getScaledInstance(LabelImage.getWidth(), LabelImage.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(image, icon.getDescription());
            LabelImage.setIcon(icon);
        }
    }//GEN-LAST:event_listWordSelectValueChanged
    /**
     * chọn chủ đề để thu hẹp phạm vi tìm từ
     * @param evt 
     */
    private void BoxTopicAndAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxTopicAndAllActionPerformed
        if( BoxTopicAndAll.getSelectedItem().toString().equals( "ALL" )) {
            ChuDe allWord = new ChuDe();
            for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() )
                for( TuVung tv : cd.getDanhSachTu() ) {
                    allWord.addTu(tv);
                }
            // sắp xếp lại tất cả các từ            
            Collections.sort(allWord.getDanhSachTu(),new WordComparator());  
            Iterator wtf =allWord.getDanhSachTu().iterator();
            // đưa dữ liệu (tất cả các từ ) vào danh sách thả xuống
            mod = new DefaultListModel<>();
            listWordSelect.setModel(mod);
            arr = new ArrayList<>();
            for( TuVung tv : allWord.getDanhSachTu() ) {
                arr.add(tv);
                mod.addElement(tv.getTenTu());
            }

            return;
        }
        formWindowOpenedNew(evt);
    }//GEN-LAST:event_BoxTopicAndAllActionPerformed

    /**
     * hàm main chính
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraCuuTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraCuuTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraCuuTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraCuuTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraCuuTuVung().setVisible(true);
            }
        }); 
        // khởi tạo dữ liệu cho chủ đề
        IOFile.inputChuDe(BienToanCuc.duLieu1);
        IOFile.inputTuVung(BienToanCuc.duLieu1);

        for( ChuDe cd : BienToanCuc.duLieu1.getDanhSachChuDe() ) {
            Collections.sort(cd.getDanhSachTu(),new WordComparator());  
            Iterator wtf =cd.getDanhSachTu().iterator(); 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxTopicAndAll;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JTextPane PaneTenTu;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField keyWord;
    private javax.swing.JList<String> listWordSelect;
    private javax.swing.JTextPane paneNghia;
    private javax.swing.JTextPane panePhienAm;
    private javax.swing.JTextPane paneTuLoai;
    // End of variables declaration//GEN-END:variables

    
}
